moderatorsTwitch = ["twitchname1", "twitchname2"]
moderatorsMinecraft = ["User321", "iGoodie"]

[[streamers]]
	minecraftNick = "minecraftNick"
	twitchNick = "twitchNick"
	platform = "STREAMLABS"
	token = "astring"
