# Displaying style of the event messages. Can be:
# "titles" to display on titles in the middle of screen
# "chat" to display on chatbox
# "disabled" to fully disable
messageDisplay="titles"

# Pitch of the notification sound
# Min: 0.0 - Max: 1.0
# Alternatively -1.0 for random pitch each time
notificationPitch=1.0

# Delay between each event to be handled
# Unit of it is milliseconds (5000 milliseconds = 5 seconds)
# Min: 0
notificationDelay=5000

# Volume of the notification sound
# Min: 0.0 - Max: 1.0
notificationVolume=1.0

# Displaying style of the status indicator. Can be:
# "enabled" to fully enable
# "circle_only" to show the circle only, without the logo
# "disabled" to fully disable
indicatorDisplay="disabled"
